const shell=document.querySelector('.messenger-shell');
document.querySelectorAll('.conversation-row').forEach((row)=>row.addEventListener('click',()=>{document.querySelectorAll('.conversation-row').forEach(r=>r.classList.remove('active'));row.classList.add('active');row.querySelector('.unread-count')?.remove();shell?.classList.add('chat-open')}));
document.querySelector('#mobileBack')?.addEventListener('click',()=>shell.classList.remove('chat-open'));
const composer=document.querySelector('#modernComposer'),input=document.querySelector('#messageInput'),area=document.querySelector('#messageArea');
composer?.addEventListener('submit',(event)=>{event.preventDefault();const value=input.value.trim();if(!value)return;const bubble=document.createElement('div');bubble.className='bubble me';bubble.innerHTML=`${value}<small>jetzt ✓</small>`;area.appendChild(bubble);input.value='';area.scrollTop=area.scrollHeight;setTimeout(()=>{const reply=document.createElement('div');reply.className='bubble them';reply.innerHTML='Das klingt interessant – erzähl mir mehr 😊<small>jetzt</small>';area.appendChild(reply);area.scrollTop=area.scrollHeight},900)});
document.querySelector('.emoji-toggle')?.addEventListener('click',()=>{input.value+=' 😊';input.focus()});
document.querySelector('#filterToggle')?.addEventListener('click',(event)=>{document.querySelector('#advancedFilters')?.classList.toggle('show');event.currentTarget.textContent=document.querySelector('#advancedFilters')?.classList.contains('show')?'Filter schließen':'Filter anzeigen'});
document.querySelector('#applyFilters')?.addEventListener('click',()=>{const count=document.querySelector('#resultCount');if(count)count.textContent='3';const button=document.querySelector('#applyFilters');button.textContent='Filter angewendet ✓';setTimeout(()=>button.textContent='Ergebnisse anzeigen',1600)});
document.querySelectorAll('[data-interest]').forEach(button=>button.addEventListener('click',()=>{button.classList.toggle('selected');button.textContent=button.classList.contains('selected')?'♥ Interesse gesendet':'♡ Interessiert'}));
